Traceback (most recent call last):
  File "/hpc/home/etb28/coganlab/etb28/GlobalLocal/dcc_scripts/spec/plot_wavelets_dcc.py", line 57, in <module>
    main(args.subject)
  File "/hpc/home/etb28/coganlab/etb28/GlobalLocal/dcc_scripts/spec/plot_wavelets_dcc.py", line 31, in main
    spec = load_wavelets(subject_id, layout, output_name, rescaled)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/home/etb28/coganlab/etb28/GlobalLocal/src/analysis/spec/wavelet_functions.py", line 464, in load_wavelets
    spec = load_tfrs(filensame)
                     ^^^^^^^^^
NameError: name 'filensame' is not defined. Did you mean: 'filename'?
