Traceback (most recent call last):
  File "/hpc/home/rl330/coganlab/rl330/GlobalLocal/src/analysis/pac/theta_connect.py", line 161, in <module>
    compute_and_plot_connectivity(
  File "/hpc/home/rl330/coganlab/rl330/GlobalLocal/src/analysis/pac/theta_connect.py", line 85, in compute_and_plot_connectivity
    con = spectral_connectivity_time(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: spectral_connectivity_time() got an unexpected keyword argument 'directed'
