Traceback (most recent call last):
  File "/hpc/home/rl330/coganlab/rl330/GlobalLocal/src/analysis/pac/theta_connect.py", line 161, in <module>
    compute_and_plot_connectivity(
  File "/hpc/home/rl330/coganlab/rl330/GlobalLocal/src/analysis/pac/theta_connect.py", line 105, in compute_and_plot_connectivity
    raise ValueError(f"Channels not found in epochs: {missing}")
ValueError: Channels not found in epochs: ['TOL1', 'TOL2']
